[package]
name = "photoflow"
version = "0.1.0"
edition = "2021"

[features]
default = ["wayland"]
wayland = ["slint/backend-winit-wayland"]
x11 = ["slint/backend-winit-x11"]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
gilrs = "0.11"
image = "0.25"
i-slint-backend-winit = "1.9"
libheif-rs = "1.1"
nom-exif = "2.2"
rayon = "1.10"
rusqlite = "0.33"
serde = "1.0"
serde_derive = "1.0"
slint = { version = "1.9", default-features = false, features = ["renderer-femtovg", "compat-1-2"] }
toml = "0.8"
walkdir = "2.5"


[build-dependencies]
slint-build = "1.9"