component EveryFrameTimerInner {
    width: 0px;
    height: 0px;

    callback triggered(dt: duration);

    private property <duration> time-now: animation-tick();
    private property <duration> time-pre;

    init => {
        time-pre = time-now;
    }

    changed time-now => {
        triggered(time-now - time-pre);
        time-pre = time-now;
    }
}

export component EveryFrameTimer {
    width: 0px;
    height: 0px;

    in property <bool> active;
    callback triggered(dt: duration);

    if active: EveryFrameTimerInner {
        triggered(dt) => {
            parent.triggered(dt);
        }
    }
}
