export global GamepadKey {
    out property <string> ActUp;
    out property <string> ActRight;
    out property <string> ActDown;
    out property <string> ActLeft;

    out property <string> DPadUp;
    out property <string> DPadRight;
    out property <string> DPadDown;
    out property <string> DPadLeft;

    out property <string> MenuMain;
    out property <string> MenuLeft;
    out property <string> MenuRight;

    out property <string> TriggerL1;
    out property <string> TriggerL2;
    out property <string> TriggerR1;
    out property <string> TriggerR2;

    public function set_actions(up: string, right: string, down: string, left: string) {
        self.ActUp = up;
        self.ActRight = right;
        self.ActDown = down;
        self.ActLeft = left;
    }

    public function set_dpad(up: string, right: string, down: string, left: string) {
        self.DPadUp = up;
        self.DPadRight = right;
        self.DPadDown = down;
        self.DPadLeft = left;
    }

    public function set_menupad(main: string, left: string, right: string) {
        self.MenuMain = main;
        self.MenuLeft = left;
        self.MenuRight = right;
    }

    public function set_triggers(l1: string, l2: string, r1: string, r2: string) {
        self.TriggerL1 = l1;
        self.TriggerL2 = l2;
        self.TriggerR1 = r1;
        self.TriggerR2 = r2;
    }
}
