import { VerticalScrollable } from "vertical-scrollable.slint";

export struct ViewModelItem {
    index: int,
    image: image,
}

export component ImageGrid inherits VerticalScrollable {
    // Visual config
    in property <length> content-pad-size: 4px;
    in property <length> img-size: 235px;
    in property <length> img-pad-size: 2px;

    // Model setup
    in property <int> item-count: 0;
    in property <[ViewModelItem]> view-model;
    pure callback set-view-model-range(int, int) -> bool;

    // Hack to auto-synchronise view-model range
    in property <bool> is-visible: true;
    visible: visibility-hook(is-visible);

    pure function visibility-hook(value: bool) -> bool {
        if (value) {
            set-view-model-range(model-offset, model-length);
        }
        value
    }

    // Item size
    property <length> item-size: self.img-size + 2 * self.img-pad-size;

    // Rows & cols
    property <int> cols: min(floor(self.width / self.item-size), self.item-count);
    property <int> rows: cols == 0 ? 0 : ceil(self.item-count / self.cols);

    // Contents
    contents-w: self.width;
    contents-h: item-size * rows;

    // View Model Items & Selection Indicator
    out property <int> selected-idx: 0;

    Rectangle {
        width: root.item-size * root.cols;
        height: root.item-size * root.rows;
        x: (root.width - self.width) * 0.5;

        for item in root.view-model: Rectangle {
            width: root.item-size;
            height: root.item-size;
            x: root.item-pos-x(item.index);
            y: root.item-pos-y(item.index);
            Image {
                width: root.img-size;
                height: root.img-size;
                x: root.img-pad-size;
                y: root.img-pad-size;
                source: item.image;
            }
        }

        Rectangle {
            visible: root.item-count > 0;
            width: root.item-size;
            height: root.item-size;
            x: root.item-pos-x(root.selected-idx);
            y: root.item-pos-y(root.selected-idx);
            border-width: root.img-pad-size;
            border-color: white;
        }
    }

    pure function item-col(index: int) -> int {
        mod(index, cols)
    }

    pure function item-row(index: int) -> int {
        floor(index / cols)
    }

    pure function item-pos-x(index: int) -> length {
        item-col(index) * item-size
    }

    pure function item-pos-y(index: int) -> length {
        item-row(index) * item-size
    }

    // Move selection API
    public function mv-selection-right() {
        if (selected-idx < item-count - 1 && item-col(selected-idx + 1) > item-col(selected-idx)) {
            selected-idx += 1;
        }
    }

    public function mv-selection-left() {
        if (selected-idx > 0 && item-col(selected-idx - 1) < item-col(selected-idx)) {
            selected-idx -= 1;
        }
    }

    public function mv-selection-up() {
        if (selected-idx - cols >= 0) {
            selected-idx -= cols;
            update-scrolling-spring();
        }
    }

    public function mv-selection-down() {
        if (selected-idx + cols < item-count) {
            selected-idx += cols;
            update-scrolling-spring();
        }
    }

    // Viewport Scrolling
    property <length> viewport-start: self.viewport-y;
    property <length> viewport-end: self.viewport-start + self.height;

    property <length> curr-item-start: item-pos-y(selected-idx);
    property <length> curr-item-end: self.curr-item-start + item-size;

    property <length> extra-scroll: item-size * 0.255;

    function update-scrolling-spring() {
        if (self.viewport-start > self.curr-item-start) {
            set-viewport-pos(self.curr-item-start - extra-scroll);
        } else if (self.viewport-end < self.curr-item-end) {
            set-viewport-pos(curr-item-end - self.height + extra-scroll);
        }
    }

    property <length> viewport-min: 0 - content-pad-size;
    property <length> viewport-max: self.contents-h - self.height + content-pad-size;

    function set-viewport-pos(pos: length) {
        self.set-spring-scroll-target(clamp(pos, viewport-min, viewport-max))
    }

    // Visible Range Reporting
    property <int> min-visible-row: floor(self.viewport-start / item-size);
    property <int> max-visible-row: ceil(self.viewport-end / item-size);

    property <int> model-offset: clamp(min-visible-row * cols, 0, max(item-count - 1, 0));
    property <int> model-length: clamp(max-visible-row * cols - model-offset, 0, max(item-count - model-offset, 0));
}
