import { ImageGrid, ImageGridItem } from "image-grid.slint";

export global MediaSource {
    pure callback set-index(int);
    pure callback clear();
    in property <image> image;
}

export enum Mode {
    Gallery,
    Viewer
}

export component PhotoFlowApp inherits Window {
    background: black;

    in-out property <Mode> mode: Gallery;

    in property <int> item-count;
    property <int> selected-idx;
    property <int> max-selected-idx: max(0, item-count - 1);

    in property <[ImageGridItem]> grid-model;
    pure callback set-grid-visible-range(int, int);
    property <length> prev-viewport-pos;

    callback close();

    if mode == Mode.Gallery: ImageGrid {
        item-count: root.item-count;
        model: root.grid-model;

        set-visible-range(offset, length) => {
            root.set-grid-visible-range(offset, length)
        }

        init => {
            self.set-selected-idx(root.selected-idx, root.prev-viewport-pos);
            grid-focus-scope.focus();
        }

        grid-focus-scope := FocusScope {
            key-pressed(event) => {
                if (event.text == Key.RightArrow) {
                    parent.mv-selection-right();
                } else if (event.text == Key.LeftArrow) {
                    parent.mv-selection-left();
                } else if (event.text == Key.UpArrow) {
                    parent.mv-selection-up();
                } else if (event.text == Key.DownArrow) {
                    parent.mv-selection-down();
                } else if (event.text == Key.Return) {
                    parent.set-visible-range(0, 0);
                    root.prev-viewport-pos = parent.viewport-y;
                    root.selected-idx = parent.selected-idx;
                    root.mode = Mode.Viewer;
                } else if (event.text == Key.Escape) {
                    root.close();
                }
                accept
            }
        }
    }

    if mode == Mode.Viewer: Image {
        width: 100%;
        height: 100%;
        image-fit: contain;
        source: MediaSource.image;

        init => {
            MediaSource.set-index(root.selected-idx);
            img-focus-scope.focus();
        }

        img-focus-scope := FocusScope {
            key-pressed(event) => {
                if (event.text == Key.RightArrow) {
                    root.selected-idx = clamp(root.selected-idx + 1, 0, root.max-selected-idx);
                    MediaSource.set-index(root.selected-idx);
                } else if (event.text == Key.LeftArrow) {
                    root.selected-idx = clamp(root.selected-idx - 1, 0, root.max-selected-idx);
                    MediaSource.set-index(root.selected-idx);
                } else if (event.text == Key.Escape) {
                    MediaSource.clear();
                    root.mode = Mode.Gallery;
                }
                accept
            }
        }
    }
}
