import { ImageGrid, ViewModelItem } from "image-grid.slint";

export component PhotoFlowApp inherits Window {
    background: black;
    forward-focus: focus-scope;

    in property <int> item-count <=> grid.item-count;
    in property <[ViewModelItem]> view-model <=> grid.view-model;
    pure callback set-view-model-range <=> grid.set-view-model-range;

    grid := ImageGrid { }

    focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.RightArrow) {
                grid.mv-selection-right();
            } else if (event.text == Key.LeftArrow) {
                grid.mv-selection-left();
            } else if (event.text == Key.UpArrow) {
                grid.mv-selection-up();
            } else if (event.text == Key.DownArrow) {
                grid.mv-selection-down();
            }
            accept
        }
    }
}
