import { SpringConfig, SpringState, Spring } from "spring-animation.slint";

export enum ViewerState {
    Loading,
    Loaded,
    FailedToLoad
}

export struct MediaViewerModel {
    state: ViewerState,
    file-name: string,
    image: image,
}

export component MediaViewer inherits Rectangle {
    width: 100%;
    height: 100%;
    clip: true;

    in property <MediaViewerModel> model;

    if model.state != ViewerState.FailedToLoad: Image {
        width: 100%;
        height: 100%;
        image-fit: contain;
        source: model.image;
    }

    spinner := Image {
        x: parent.width - self.width;
        y: parent.height - self.height;
        source: @image-url("img/spinner.svg");
        rotation-angle: 360deg * mod(animation-tick(), 2s) / 2s;
        opacity: 0;

        property <float> traget-opacity: model.state == ViewerState.Loading ? 1 : 0;
        changed traget-opacity => { spinner-opacity-spring.update-target(); }
    }

    spinner-opacity-spring := Timer {
        interval: 1s / 60;
        running: Spring.is-active(state);

        property <SpringState> state;
        property <SpringConfig> config: { stiffness: 500, damping: 40, mass: 1 };

        function update-target() {
            state = Spring.start(spinner.opacity, spinner.traget-opacity, state.velocity);
        }

        triggered => {
            state = Spring.update(config, state, self.interval / 1s);
            spinner.opacity = state.current-value;
        }
    }

    if model.state == ViewerState.FailedToLoad: Text {
        text: model.file-name;
        color: white;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
}
