export struct SpringConfig {
    mass: float,
    stiffness: float,
    damping: float,
}

export struct SpringState {
    current-value: float,
    target-value: float,
    velocity: float,
}

export global Spring {
    public pure function start(curr: float, target: float, velocity: float) -> SpringState {
        {
            current-value: curr,
            target-value: target,
            velocity: velocity,
        }
    }

    public pure function update(cfg: SpringConfig, state: SpringState, dt: float) -> SpringState {
        let displacement = state.current-value - state.target-value;
        let stifness-force = -displacement * cfg.stiffness;
        let damping-force = -state.velocity * cfg.damping;
        let velocity = state.velocity + (stifness-force + damping-force) / cfg.mass * dt;

        let updated-state = {
            velocity: velocity,
            current-value: state.current-value + velocity * dt,
            target-value: state.target-value
        };

        if (is-calmed(updated-state)) {
            { velocity: 0, current-value: state.target-value, target-value: state.target-value }
        } else {
            updated-state
        }
    }

    public pure function is-active(state: SpringState) -> bool {
        !is-calmed(state)
    }

    pure function is-calmed(state: SpringState) -> bool {
        let displacement = state.current-value - state.target-value;
        abs(displacement) < 0.001 && abs(state.velocity) < 0.001
    }
}
