import { SpringConfig, SpringState, Spring } from "spring-animation.slint";
import { EveryFrameTimer } from "every-frame-timer.slint";

export component VerticalScrollable inherits Rectangle {
    width: 100%;
    height: 100%;
    clip: true;

    in property <length> contents-w;
    in property <length> contents-h;

    in-out property <length> viewport-x;
    in-out property <length> viewport-y;

    public function set-spring-scroll-target(target: length) {
        scroll-animator.start(target);
    }

    scroll-animator := EveryFrameTimer {
        active: Spring.is-active(state);

        private property <SpringState> state;
        private property <SpringConfig> config: { stiffness: 700, damping: 40, mass: 1 };

        function start(target: length) {
            state = Spring.start(root.viewport-y / 1px, target / 1px, state.velocity);
        }

        triggered(dt) => {
            state = Spring.update(config, state, dt / 1s);
            parent.viewport-y = state.current-value * 1px;
        }
    }

    Rectangle {
        x: -root.viewport-x;
        y: -root.viewport-y;
        width: root.contents-w;
        height: root.contents-h;
        @children
    }
}
